

export let hgmfArr = [
    { "name": "h-g-m-f-id", "type": "int", "min": 1, "max": 100, "default": 1 },
    { "name": "h-g-m-f-status", "min": 0, "static": false, "type": "string", "max": 8 },
    { "name": "h-g-m-f-received_time_stamp", "type": "timestamp", "tsformat": "default" },
    { "name": "h-g-m-f-selector", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-name", "default": "General Report Data", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-display_name", "default": "General TLV", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-gpsstatus_index", "type": "int", "min": 1, "max": 100, "default": 1 },
    { "name": "h-g-m-f-num_satellites", "type": "int", "min": 1, "max": 1000000000, "default": 100 },
    { "name": "h-g-m-f-hdop", "type": "int", "min": 1, "max": 1000000000, "default": 10000000 },
    { "name": "h-g-m-f-external_power_volts", "type": "float", "min": 1, "max": 23, "precision": 1 },
    { "name": "h-g-m-f-internal_power_volts", "type": "float", "min": 1, "max": 20, "precision": 2 },
    { "name": "h-g-m-f-odometer_kms", "type": "float", "min": 1, "max": 5000000, "precision": 1 },
    { "name": "h-g-m-f-latitude", "type": "location", "lat": 39.943436, "long": -74.915885, "radius": 1000000 },
    { "name": "h-g-m-f-altitude_feet", "type": "int", "min": 1, "max": 1000000000000, "default": 1000000000 },
    { "name": "h-g-m-f-speed_kms", "type": "int", "min": 1, "max": 1000000, "default": 0 },
    { "name": "h-g-m-f-heading", "type": "int", "min": 1, "max": 1000, "default": 100 },
    { "name": "h-g-m-f-rssi", "type": "int", "min": 1, "max": 1000, "default": 100 },
    { "name": "h-g-m-f-gps_time", "type": "timestamp", "tsformat": "default" },
    { "name": "h-g-m-f-power", "default": "external", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-trip", "default": "Off", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-ignition", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-motion", "default": "Off", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-shipping_mode", "default": "Off", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-vib_trip", "default": "Off", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-charger", "default": "Off", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-tamper", "default": "Off", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-odometer_field", "default": "enabled", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-status_field", "default": "enabled", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-ext_int_power", "default": "enabled", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-gps_field", "default": "enabled", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-altitude_field", "default": "enabled", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-speedheading_field", "default": "enabled", "min": 0, "static": false, "type": "string", "max": 24 },
    { "name": "h-g-m-f-speed_miles", "type": "int", "min": 1, "max": 100, "default": 0 }
]
