export let randomArr = [
	{ name: '_index', default: 'device_report_data_live', min: 0, static: false, type: 'string', max: 36 },
	{ name: '_type', default: '_doc', min: 0, static: false, type: 'string', max: 24 },
	{ name: '_id', min: 0, static: false, type: 'string', max: 24 },
	{ name: '_score', type: 'int', min: 1, max: 100000, default: 1 },
	{ name: 'r_header-device_id-keyword', min: 0, static: false, type: 'string', max: 16 },
	{ name: 'ih-mr-h-total-value', type: 'int', min: 1, max: 10000, default: 5000 },
	{ name: 'ih-mr-h-total-relation', default: 'eq', min: 0, static: false, type: 'string', max: 4 },
	{ name: 'ih-mr-h-max_score', min: 0, static: false, type: 'string', max: 6 },
	{ name: 'h-_indexs', default: 'device_report_data_live', min: 0, static: false, type: 'string', max: 24 },
	{ name: 'h-_type', default: '_doc', min: 0, static: false, type: 'string', max: 24 },
	{ name: 'h-_id', min: 0, static: false, type: 'string', max: 24 },
	{ name: 'h-_score', min: 0, static: false, type: 'string', max: 24 },
	{ name: 'h-sort', type: 'timestamp', tsformat: 'default' },
	{ name: 's-sort', type: 'timestamp', tsformat: 'default' },
	{ name: 'device_id', min: 0, static: false, type: 'string', max: 12 },
];
