


let voltageArr = [
    {"name":"h-voltage-id","default":"","min":1,"type":"int","max":10000000000},
    {"name":"h-voltage-status","min":0,"static":false,"type":"string","max":12},
    {"name":"h-voltage-received_time_stamp","type":"timestamp","tsformat":"default"},
    {"name":"h-voltage-selector","type":"int","min":1,"max":1000000000,"default":100},
    {"name":"h-voltage-name","default":"voltage","min":0,"static":false,"type":"string","max":24},
    {"name":"h-voltage-display_name","default":"voltage","min":0,"static":false,"type":"string","max":24},
    {"name":"h-voltage-main_power","type":"float","min":1,"max":20,"precision":3},
    {"name":"h-voltage-aux_power","type":"float","min":1,"max":20,"precision":3},    
    {"name":"h-voltage-charge_power","type":"int","min":1,"max":10,"default":1},
    {"name":"h-voltage-battery_power","type":"float","min":1,"max":200,"precision":3},
    {"name":"s-voltage-id","default":"","min":1,"type":"int","max":100000},
    {"name":"s-voltage-status","min":0,"static":false,"type":"string","max":12},
    {"name":"s-voltage-received_time_stamp","type":"timestamp","tsformat":"default"},
    {"name":"s-voltage-selector","type":"int","min":1,"max":1000000000,"default":100},
    {"name":"s-voltage-name","default":"voltage","min":0,"static":false,"type":"string","max":24},
    {"name":"s-voltage-display_name","default":"voltage","min":0,"static":false,"type":"string","max":24},
    {"name":"s-voltage-main_power","type":"float","min":1,"max":20,"precision":3},
    {"name":"s-voltage-aux_power","type":"float","min":1,"max":20,"precision":3},    
    {"name":"s-voltage-charge_power","type":"int","min":1,"max":10,"default":1},
    {"name":"s-voltage-battery_power","type":"float","min":1,"max":200,"precision":3},
    {"name":"s-voltage-id","default":"","min":1,"type":"int","max":100000},
    {"name":"s-voltage-status","min":0,"static":false,"type":"string","max":12},
    {"name":"s-voltage-received_time_stamp","type":"timestamp","tsformat":"default"},
    {"name":"s-voltage-selector","type":"int","min":1,"max":1000000000,"default":100},
    {"name":"s-voltage-name","default":"voltage","min":0,"static":false,"type":"string","max":24},
    {"name":"s-voltage-display_name","default":"voltage","min":0,"static":false,"type":"string","max":24},
    {"name":"s-voltage-main_power","type":"float","min":1,"max":20,"precision":3},
    {"name":"s-voltage-aux_power","type":"float","min":1,"max":20,"precision":3},    
    {"name":"s-voltage-charge_power","type":"int","min":1,"max":10,"default":1},
    {"name":"s-voltage-battery_power","type":"float","min":1,"max":200,"precision":3}
]