name: DEV Full Regression
on:
  schedule:
    - cron: '30 6 * * *'

  workflow_dispatch:
    inputs:
      spec:
        description: 'Enter specifications in format:
          --spec "cypress/e2e"'
        required: false
        default: ''
        type: string

jobs:
  build-project:
    name: DEV regression suite run
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.2'

      - name: Install Node modules
        run: npm install

      - name: Run Cypress (DEV)
        env:
          CLIENT_ID: 6j2mbpt4dcv207qikq9b4ph47c
          USERNAME: test1
          PASSWORD: ${{ secrets.QA_AWS_PASSWORD }}
        run: npx cypress run --env fileConfig=dev ${{ github.event.inputs.spec }}
        continue-on-error: true

      - name: 'Upload test results'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cypress/results/
          retention-days: 30

      - name: 'Upload screenshots'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots
          path: cypress/screenshots/
          retention-days: 30

  release-project:
    name: xray result submittal
    runs-on: windows-latest
    needs: build-project
    steps: 

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 'download test results'
        if: ${{ always() }}
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: cypress/test-results/

      - name: Submit results to Xray
        uses: mikepenz/xray-action@v2.4.5
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_SECRET }}
          testFormat: "junit"
          testPaths: "**/test-results/*.xml"
          testExecutionJson: "cypress/test-exec/DEV-test-execution.json"
          projectKey: "PRJIND"
          # testEnvironments: "QA, DEV"
          # testExecKey: "PRJIND-2629"
          failOnImportError: true