name: Run tests
on:
  schedule:
    - cron:  '30 8 * * *'

  workflow_dispatch:
    inputs:
      env:
        description: 'Select environment'
        required: true
        default: 'qa' 
        type: choice
        options:
        - dev
        - qa
      spec:
        description: 'Enter specifications in format     :
                        --spec "cypress/e2e"'
        required: false
        default: ''
        type: string

jobs:
  cypress:
    name: Run Cypress
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.2'

      - name: Install Node modules
        run: npm install

      - name: Run Cypress (DEV)
        env:
          CLIENT_ID: 2652adm3ps89eqhr5ap54kd85i
          USERNAME: qa_automation
          PASSWORD: ${{ secrets.DEV_AWS_PASSWORD }}
        if: "${{ github.event.inputs.env == 'dev' || github.event.inputs.env == '' }}"
        run:  npx cypress run --env dev=1 ${{ github.event.inputs.spec }}
        continue-on-error: true

      - name: Run Cypress (QA)
        env:
          CLIENT_ID: 584mrs4de25a4iqok485b6vhnc
          USERNAME: qa_automation
          PASSWORD: ${{ secrets.QA_AWS_PASSWORD }}
        if: "${{ github.event.inputs.env == 'qa' }}"
        run: npx cypress run --env qa=1 ${{ github.event.inputs.spec }}
        continue-on-error: true
        
      - name: 'Upload test results'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/
          retention-days: 30

      - name: 'Upload screenshots'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots
          path: cypress/screenshots/
          retention-days: 30

      - name: 'Upload video'
        if: github.event.inputs.env != ''
        uses: actions/upload-artifact@v3
        with:
          name: test-video
          path: cypress/video/
          retention-days: 30
