### Placeholder workflow
name: Run tests
on:
  workflow_dispatch: {}

jobs:
  cypress:
    name: Run Cypress
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Echo repo dir
        run: ls -lah .
