name: Run Tests
on:
  schedule:
    - cron: '30 8 * * *'

  workflow_dispatch:
    inputs:
      env:
        description: 'Select environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
      spec:
        description: 'Enter specifications in format:
          --spec "cypress/e2e"'
        required: false
        default: ''
        type: string

jobs:
  build-project:
    name: QA regression suite run
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.2'

      - name: Install Node modules
        run: npm install

      - name: Run Cypress (QA)
        env:
          CLIENT_ID: 584mrs4de25a4iqok485b6vhnc
          USERNAME: test1
          PASSWORD: ${{ secrets.QA_AWS_PASSWORD }}
        if: "${{ github.event.inputs.env.default == 'qa' || github.event.inputs.env.default == '' }}"
        run: npx cypress run --env fileConfig=qa ${{ github.event.inputs.spec }}
        continue-on-error: true

      - name: 'Upload test results'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cypress/results/
          retention-days: 30

      - name: 'Upload screenshots'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots
          path: cypress/screenshots/
          retention-days: 30

  release-project:
    name: xray result submittal
    runs-on: windows-latest
    needs: build-project
    steps: 

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 'download test results'
        if: ${{ always() }}
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: cypress/test-results/

      - name: Submit results to Xray
        uses: mikepenz/xray-action@v2
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_SECRET }}
          testFormat: "junit"
          testPaths: "**/test-results/*.xml"
          testExecutionJson: "cypress/test-exec/QA-test-execution.json"
          testEnvironments: "QA, DEV"
          projectKey: "PRJIND"
          failOnImportError: true

      - name: Final Xray submittal
        env:
            JIRA_SERVER_URL: ${{ secrets.JIRA_SERVER_URL }}
            JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
            JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        run: 'curl -H "Content-Type: multipart/form-data" -u ${JIRA_USERNAME}:${JIRA_PASSWORD} -F "file=C:\Users\RUNNER~1\AppData\Local\Temp\tmp.*.xml" "${JIRA_SERVER_URL}/rest/raven/1.0/import/execution/junit?projectKey=PRJIND"'
    